refactor actions 8

diff --git a/project/scripts/local/run-test b/project/scripts/local/run-test
--- a/project/scripts/local/run-test
+++ b/project/scripts/local/run-test
@@ -2,10 +2,28 @@
 
 set -eou pipefail
 
-export MONGO_INITDB_USERNAME=test-user
-export MONGO_INITDB_PASSWORD=oNVnSwoivIxQss5c
-export MONGO_CLUSTER=cluster0.hhxxk.mongodb.net
-export PORT=3100
-export MONGO_INITDB_DATABASE=rest-api-test
+env_file=".env.test"
+
+if [[ ! -f $env_file ]]; then
+  echo -e "\e[1;31m$env_file not found\e[0m"
+  exit 1
+fi
+
+function getenv {
+  local var_name=$1
+  local var_value=$(grep "$var_name" $env_file | cut -d '=' -f 2)
+  if [[ -z $var_value ]]; then
+    echo -e "\e[1;31m$var_name not found in .env.test\e[0m"
+    exit 1
+  fi
+  echo "$var_value"
+};
+
+
+export MONGO_INITDB_USERNAME=$(getenv "MONGO_INITDB_USERNAME")
+export MONGO_INITDB_PASSWORD=$(getenv "MONGO_INITDB_PASSWORD")
+export MONGO_CLUSTER=$(getenv "MONGO_CLUSTER")
+export PORT=$(getenv "PORT")
+export MONGO_INITDB_DATABASE=$(getenv "MONGO_INITDB_DATABASE")
 
 bash scripts/test --build
